### ISSUE TITLE
Code release date?

### ISSUE THREAD

**Issue by Devetec** [THUDM/CogView#1]
Is it possible to give an approximate date that the code and models will be released? By the way, this model looks amazing, thank you for planning to make it open-source.

Thanks, devetec

**Comment by Sleepychord** [comment]
Hi devetec,
Thank you for interests in our work. We will release after an internal process in BAAI (an organization like MILA in Beijing), which I expect to finish before 6.15, but this is only an estimated date.

**Comment by johnpaulbin** [comment]
Released today
