### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by ak9250** [THUDM/CogView#10]
please add a google colab for inference thanks

**Comment by johnpaulbin** [comment]
Hi! I'm currently working on this issue.

**Comment by Sleepychord** [comment]
@ak9250 @johnpaulbin Good idea, I will try it but since it is not easy to push things to google in China, it might take some times.

**Comment by johnpaulbin** [comment]
> @ak9250 @johnpaulbin Good idea, I will try it but since it is not easy to push things to google in China, it might take some times.

This is what I was worried about, once I do get my hands on the pre-trained model, I will have the colab open to only few until I see updates on the matter.

**Comment by Sleepychord** [comment]
Thanks @johnpaulbin . If you're working on this, report any encountered problems in the issues.

**Comment by johnpaulbin** [comment]
> Thanks @johnpaulbin . If you're working on this, report any encountered problems in the issues.

Hey there @Sleepychord I finished the colab for inferencing, requires a Colab Pro account. It includes the model download as well. 
https://colab.research.google.com/drive/1Bi2TnSUp2vNiSUhamsNuC4HqkZ2J4WwZ?usp=sharing

**Comment by fuzzbuck** [comment]
here is an alternative that works with colab standard runtime (non-pro)
https://colab.research.google.com/drive/1ahsm15makBon5DZMy64a76TTWePBBp5l

**Comment by Sleepychord** [comment]
Con! @johnpaulbin @fuzzbuck Thank you for your efforts! I have add links to your colabs to readme.md~

**Comment by Mimocro** [comment]
https://github.com/THUDM/CogView/issues/10#issuecomment-863590452
Please add a torrent download method in colab or update links. 
Also this works https://github.com/nishan7/Google-Colab-Torrent-Downloader with some modifications and its a way faster than wget.

**Comment by fuzzbuck** [comment]
> 
> 
> [#10 (comment)](https://github.com/THUDM/CogView/issues/10#issuecomment-863590452)
> Please add a torrent download method in colab or update links.
> Also this works https://github.com/nishan7/Google-Colab-Torrent-Downloader with some modifications and its a way faster than wget.

if you are able to provide a simple working solution and add it into the notebook, please contact me on discord
aze#0001

**Comment by flarn2006** [comment]
> here is an alternative that works with colab standard runtime (non-pro) https://colab.research.google.com/drive/1ahsm15makBon5DZMy64a76TTWePBBp5l

Is it just me or are most of the input cells here blank?

**Comment by MichaelMaiii** [comment]
> 

Same problem, the input cells are blank.

**Comment by Mimocro** [comment]
@flarn2006, @MichaelMaiii, here is a backup from 13 august.
https://colab.research.google.com/drive/1FXamcknVcOa7eYKarZY4CWAmZeNCYwPM?usp=sharing

I don't know why, but on october 22, aze (@fuzzbuck) cleared some cells.

**Comment by dhruvrnaik** [comment]
Hi, the cogview_base.tar file cannot be downloaded. Seems like the-eye.eu has shut down. Is there an alternative link to download the model?
