### ISSUE TITLE
Can't apply to download model.

### ISSUE THREAD

**Issue by PapayasTehSkeletor** [THUDM/CogView#11]
Good afternoon,

I tried to register on wudaoai and put in my information so I could download the model, but Wudaoai did not accept my phone number, probably because I am from Brazil. I had to look for a Chinese phone number online to apply, but I doubt they will allow me to download the model because of this. What can I do?

**Comment by johnpaulbin** [comment]
Hi! A Chinese phone number is required for application.

**Comment by afiaka87** [comment]
@johnpaulbin What is the overseas option for?

**Comment by afiaka87** [comment]
There is an overseas option which can be checked; but it results in a 500 error.

**Comment by PapayasTehSkeletor** [comment]
> Hi! A Chinese phone number is required for application.

Can I hope to be approved for the application even without the real number? I have been looking forward to the launch of Cogview since I heard about it on day 1.

**Comment by johnpaulbin** [comment]
A Chinese phone number isn't required, but is required if you did not chose the "Overseas User Login."

**Comment by SeitaroShinagawa** [comment]
@johnpaulbin 
Downloading each file requires a Chinese phone number although "Overseas User Login" is possible without it.  
I chose "Overseas User Login," and this picture shows when I click to download "cogview-base.tar" on the right. 
"有效的手机号" requires a Chinese phone number (in fact, my Japanese phone number was refused). Is it an incorrect way?

![image](https://user-images.githubusercontent.com/7993233/122145695-b27bc380-ce90-11eb-85fa-8465fa71d424.png)

**Comment by johnpaulbin** [comment]
> @johnpaulbin
> Downloading each file requires a Chinese phone number although "Overseas User Login" is possible without it.
> I chose "Overseas User Login," and this picture shows when I click to download "cogview-base.tar" on the right.
> "有效的手机号" requires a Chinese phone number (in fact, my Japanese phone number was refused). Is it an incorrect way?
> 
> ![image](https://user-images.githubusercontent.com/7993233/122145695-b27bc380-ce90-11eb-85fa-8465fa71d424.png)

@SeitaroShinagawa 

Make sure you also include the country code as well.
Example: `18008727677`
Notice the 1 at the beginning representing the country.

**Comment by SeitaroShinagawa** [comment]
@johnpaulbin 
Thank you for the quickest response. Including the country code takes longer characters than the input limitation (11 characters).  
However, when I used a dammy country code (Japan has 81, but I tried 1), I have successfully finished sending a request...

**Comment by Sleepychord** [comment]
Hi all, thanks for your reporting. I have reported this problem to the maintainer of the website. I think it will be fixed very soon. If they cannot in 1 day, I will place the weights with another links.

**Comment by johnpaulbin** [comment]
> Hi all, thanks for your reporting. I have reported this problem to the maintainer of the website. I think it will be fixed very soon. If they cannot in 1 day, I will place the weights with another links.

That sounds awesome, @Sleepychord 
Is the mirror links going to be also secured or protected behind a security check, like application too? Or would we able to download the weights directly?

**Comment by Sleepychord** [comment]
@johnpaulbin The oversea user registration has been fixed. The verification is needed to prevent malicious requests, so that we can provide a good speed for downloading. This is a rule of the BAAI website so we might not able to share a direct link.

**Comment by rishabhjain** [comment]
I keep getting `Internal System Error`. 

![cogview](https://user-images.githubusercontent.com/2570363/122192680-83c21500-ceb1-11eb-98bc-4f575e30192f.png)

**Comment by Sleepychord** [comment]
@rishabhjain You should select the "login for user outside China, not using WeChat to login"~
<img width="465" alt="image" src="https://user-images.githubusercontent.com/9153807/122205997-761d8700-ced3-11eb-9765-a6e1dcb629da.png">

**Comment by rishabhjain** [comment]
@Sleepychord Yeah, I used this one. And then got a one time password on my cellphone, which I verified. After that, I filled in my phone number, email, Institution, Department and Designationa and got `Internal Server Error`.

**Comment by fuzzbuck** [comment]
torrent mirror;
http://mirror.io.community/blob/torrents/Cogview_Models.torrent

**Comment by jp-krow** [comment]
Hey @PapayasTehSkeletor , as you may or may not have known, we've gotten access to the model. The torrent is available above this comment. I'm working on a way to use the model to inference and use CogView inside Colab.

**Comment by PapayasTehSkeletor** [comment]
> Hey @PapayasTehSkeletor , as you may or may not have known, we've gotten access to the model. The torrent is available above this comment. I'm working on a way to use the model to inference and use CogView inside Colab.

Oh yeah. I think the problem is solved then. Will close this issue right now.

**Comment by johnpaulbin** [comment]
> > Hey @PapayasTehSkeletor , as you may or may not have known, we've gotten access to the model. The torrent is available above this comment. I'm working on a way to use the model to inference and use CogView inside Colab.
> 
> Oh yeah. I think the problem is solved then. Will close this issue right now.

@PapayasTehSkeletor Colab with the direct download is here: https://colab.research.google.com/drive/1Bi2TnSUp2vNiSUhamsNuC4HqkZ2J4WwZ
