### ISSUE TITLE
Got error ''IndexError: tuple index out of range'' running super-res on colab with a tesla v100

### ISSUE THREAD

**Issue by johngore123** [THUDM/CogView#18]
/content/CogView
Generate Samples
WARNING: No training data specified
using world size: 1 and model-parallel size: 1 
 > using dynamic loss scaling
> initializing model parallel with size 1
> initializing model parallel cuda seeds on global rank 0, model parallel rank 0, and data parallel rank 0 with model parallel seed: 3952 and data parallel seed: 1234
> padded vocab (size: 58219) with 21 dummy tokens (new size: 58240)
prepare tokenizer done
building CogView2 model ...
 > number of parameters on model parallel rank 0: 3928849920
current device: 0
tcmalloc: large alloc 7881007104 bytes == 0x5637e3fb2000 @  0x7f61e428db6b 0x7f61e42ad379 0x7f6171f1e25e 0x7f6171f1f9d2 0x7f61aff48e7d 0x7f61c0b43120 0x7f61c0781bd9 0x5637152088a8 0x56371527bfd5 0x5637152767ad 0x5637152093ea 0x5637152773b5 0x5637152767ad 0x563715209003 0x563715208b09 0x56371535028d 0x5637152bf1db 0x563715207bb1 0x5637152f8fed 0x56371527b988 0x5637152767ad 0x563715148e2c 0x563715278bb5 0x5637152764ae 0x5637152093ea 0x56371527832a 0x56371520930a 0x5637152773b5 0x56371520930a 0x5637152773b5 0x5637152764ae
Load model file pretrained/cogview/cogview-sr/20000/mp_rank_00_model_states.pt
Working on No. 0 on 0... 
Traceback (most recent call last):
  File "generate_samples.py", line 326, in <module>
    main()
  File "generate_samples.py", line 323, in main
    generate_images_continually(model, args)
  File "generate_samples.py", line 215, in generate_images_continually
    for raw_text, seq, output_path in get_context(args, query_template):
  File "generate_samples.py", line 132, in get_context
    seq = _parse_and_to_tensor(raw_text, img_size=img_size, query_template=query_template)
  File "generate_samples.py", line 70, in _parse_and_to_tensor
    text = query_template.format(*text.split('\t'))
IndexError: tuple index out of range
/content

**Comment by Sleepychord** [comment]
Please follow the format in the readme.md, a.k.a. text\t{img_path}.

**Comment by johnpaulbin** [comment]
From what I can understand, inside aze's colab, this is how it is done:
```
query_template = '[ROI1] {} [BASE] [BOI1] [Image]{}'
p = '一个漂亮的女人走在街上\t/content/CogView/samples/0.jpg'
text = query_template.format(*p.split('\t'))
text
```

**Comment by johngore123** [comment]
Ok ill close for now if something new happens ill reopen

**Comment by johngore123** [comment]
Issue still happens even with all those things.

**Comment by johngore123** [comment]
Could need some more documentation.

**Comment by Sleepychord** [comment]
> Could need some more documentation.

Can you provide your input and details? \t means TAB

**Comment by johngore123** [comment]
#@title Super resolution (WIP) if you know how to implement this contact aze#0001 on discord
#@markdown this requires the cogview-sr model to be downloaded (look at the 3rd cell)

#@markdown can be 0.jpg, 1.jpg, 2.jpg ... etc depends on your batch_size
image = "0.jpg" #@param {type:"string"}

prompt = "text\t/content/CogView/samples/" + image

%cd /content/CogView
!sh scripts/super_resolution.sh
%cd /content

# 一个漂亮的女人走在街上\t/content/CogView/samples/0.jpg

**Comment by johngore123** [comment]
And those are just the default i did replace prompt =''text

**Comment by johngore123** [comment]
With Chinese text but you get the idea, i think.

**Comment by Sleepychord** [comment]
> #@title Super resolution (WIP) if you know how to implement this contact aze#1 on discord
> #@markdown this requires the cogview-sr model to be downloaded (look at the 3rd cell)
> 
> #@markdown can be 0.jpg, 1.jpg, 2.jpg ... etc depends on your batch_size
> image = "0.jpg" #@param {type:"string"}
> 
> prompt = "text\t/content/CogView/samples/" + image
> 
> %cd /content/CogView
> !sh scripts/super_resolution.sh
> %cd /content
> 
> # 一个漂亮的女人走在街上\t/content/CogView/samples/0.jpg

I am sorry but it seems the message is messy and I cannot know what you really input, but could you try to change the input source to a file? 
```
./scripts/super_resolution.sh --input-source sr_input.txt
``` 
where sr_input.txt is a line of 
```
 一个漂亮的女人走在街上\t/content/CogView/samples/0.jpg
```
\t is TAB, which looks like some spaces. The line looks like (but changing spaces to a TAB)
```
 一个漂亮的女人走在街上    /content/CogView/samples/0.jpg
```

**Comment by johngore123** [comment]
Ill try if it works ill close

**Comment by johngore123** [comment]
Still same error is there any way you could update the readme for an more detailed guide?

**Comment by johngore123** [comment]
That would help.

**Comment by johngore123** [comment]
Since nobody has gotten it to work.

**Comment by Sleepychord** [comment]
@johngore123 I think the guidance is enough, and your error message is very simple and clear: the input text cannot be split into two parts by "\t". The details mean that the printed results of `text.split('\t')` or something like that, without which I cannot offer more help.

**Comment by johngore123** [comment]
Closing forever since problem is solved

**Comment by johngore123** [comment]
Thanks for the help
