### ISSUE TITLE
Is there any way to run without apex?

### ISSUE THREAD

**Issue by veryweak** [THUDM/CogView#19]
Hi, thank you for your great work! I wonder if there is any solution or workaround to run without apex? I met some problems in installing apex on RTX 3090 due to the capability of apex.

**Comment by veryweak** [comment]
Actually, it's my bad... apex can also be installed on RTX 3090...

**Comment by laulampaul** [comment]
I face the same problem
it is hard to compile the apex

**Comment by Sleepychord** [comment]
@laulampaul Please use our provided docker.
