### ISSUE TITLE
Would you like to release the tutorials about how to train a new cogview on other language?

### ISSUE THREAD

**Issue by trouble-maker007** [THUDM/CogView#20]
I want to train a new cogview with small size on other language, I found the pretrain [script](https://github.com/THUDM/CogView/blob/main/scripts/pretrain_multiple_nodes.sh), and has some questions:
1. how to use vae to get the `vqvae_hard_biggerset_011.pt`?
2. how to generate the pretrain file `ali_vqvae_hard_biggerset_011.lmdb`? And would you like to release the `ali_vqvae_hard_biggerset_011.lmdb` in the future?
Thanks a lot

**Comment by Sleepychord** [comment]
1. The training scripts of vqvae will be released after reformatting. 2. You can use vqvae_hard_biggerset_011.pt to compress images into image tokens, but a tutorial and example dataset will be release after some days.

**Comment by trouble-maker007** [comment]
@Sleepychord Thanks for quick response. Got it
