### ISSUE TITLE
vqvae pretrained model

### ISSUE THREAD

**Issue by ToBeNormal** [THUDM/CogView#21]
Hi, thank you for your excellent work?
How can I train my own VQVAE model? or VQGAN model?

**Comment by Sleepychord** [comment]
hi, you can train the model using many relative repos on GitHub. You can replace the vqvae model as long as your model supports interfaces in vqvae/api.py.

**Comment by ToBeNormal** [comment]
Now I can train my own VQVAE model, but I have no idea how to get a VQGAN model. The code in taming-transformer saves the model as ".ckpt".

**Comment by ToBeNormal** [comment]
I train my own VQVAE and put it in the pre-trained model, but I can't generate meaningful samples. 
The generated samples by my own trained VQVAE and the provided Cogview is as follows:
![image](https://user-images.githubusercontent.com/79554332/124587552-518d4d00-de8a-11eb-9739-349ac898bff1.png)
Do I have to train Cogview again? But I don't have a database that contains items and products.

**Comment by Sleepychord** [comment]
Of course you should retrain a Cogview model, or you can only retrain the decoder part of vqvae.

**Comment by ToBeNormal** [comment]
Thank you for your reply! Do you have a plan to release the Alibaba dataset?

**Comment by Sleepychord** [comment]
@ToBeNormal After discussing with Alibaba tianchi, I found it hard for me to prepare enough materials to request a release. I will consider to split another part dataset as a demo. Please wait.

**Comment by Sleepychord** [comment]
Hi, we have already update another the example dataset, which is only about 80,000 images. The training performance should not be as good as the released CogView. It is only an example dataset to try.
