### ISSUE TITLE
How long will it take for a pre-training model application to be approved？

### ISSUE THREAD

**Issue by starmemda** [THUDM/CogView#22]
@neozhangthe1 @Sleepychord @lykeven @cenyk1230

**Comment by wy0801718** [comment]
Hi, I’m Wang from BAAI-Wudao.

Here are the answers to your question:
1.Please confirm whether you successfully registered and applied the model from **https://wudaoai.cn/model/wy** 

2.If there are mistakes, please send the application reason via email to open@baai.ac.cn
After the approval(within 2 days), we will send you the download link directly.
