### ISSUE TITLE
Hi！ How should I prepare the dataset_type of TextCodedataset in your code?

### ISSUE THREAD

**Issue by starmemda** [THUDM/CogView#23]
Hi！ How should I prepare the dataset_type of **TextCodedataset** in your code if I want to finetune the network in our data. I notice that **TextCodedataset** consists of **text** and **code**. What does the **code** mean? And how should I get it?
![QQ20210726-100221](https://user-images.githubusercontent.com/71432113/126923333-a67bbde0-aa44-4662-95de-2dbe7e2f51b8.png)
@neozhangthe1 @Sleepychord @lykeven @cenyk1230 @Somefive

**Comment by Sleepychord** [comment]
Hi, we have also add another data format, BinaryDataset. It is only a series of 64 text tokens and 1024 image tokens. You can easily generate such file yourself or by our cogdata toolkit.
