### ISSUE TITLE
Hello! CUDA out of memory when load the pretrained model of cogview-caption

### ISSUE THREAD

**Issue by starmemda** [THUDM/CogView#25]
Hello！Our team plans to load the pre-trained model of cogview-caption to finetune with v100, which is consistent with what you said in the paper about pre-training on the V100. But it turns out that "CUDA out of memory", and the training can't be launched until the model-parallel-size is set to be 4. So, how can we load the pre-trained model and finetune on V100? 
@neozhangthe1 @Sleepychord @lykeven @cenyk1230 @Somefive

**Comment by johnpaulbin** [comment]
@starmemda Here is a google colab that allows to run on only less than 12 GB of RAM: https://colab.research.google.com/drive/1ahsm15makBon5DZMy64a76TTWePBBp5l

**Comment by Sleepychord** [comment]
@starmemda Could you provide your hyperparameters? both cogview and deepspeed.

**Comment by starmemda** [comment]
> @starmemda Could you provide your hyperparameters? both cogview and deepspeed.
Here is the namespace of hyperparameters.
How should I revise it?

 Namespace(attention_dropout=0.1, batch_size=1, check_mode='code', checkpoint_activations=True, checkpoint_num_layers=1, clip_grad=1.0, cpu_optimizer=False,                       cpu_torch_adam=False, cuda=True, dataset_type='TXTDataset', debug=False, deep_init=False, deepscale=False, deepscale_config=None, deepspeed=True,                                 deepspeed_activation_checkpointing=True, deepspeed_config='/hetu_group/wuxiangyu/cx/CogView_finetune/scripts/ds_config.json', deepspeed_mpi=False, device=None,                   distributed_backend='nccl', do_test=1, do_train=1, do_valid=1, dynamic_loss_scale=True, eval_batch_size=None, eval_interval=1000, eval_iters=100, exit_interval=None,             experiment_name='cogview-caption', fast_load=False, finetune=True, fp16=True, fp32_allreduce=False, fp32_embedding=False, fp32_layernorm=False, fp32_tokentypes=False,            generation_task='text2image', gradient_accumulation_steps=1, hidden_dropout=0.1, hidden_size=2560, hysteresis=2, img_folder_path='image/', img_tokenizer_num_tokens=8192,         img_tokenizer_path=None, input_folder_path='input/', input_rec_path='input/', input_source='interactive', is_sparse=0, key_window_times=4, layernorm_epsilon=1e-05, load='./pretrained/cogview/cogview-caption/', local_rank=2, log_interval=2, loss_scale=None, loss_scale_window=1000, lr=0.0004,                  lr_decay_iters=None, lr_decay_ratio=0.1, lr_decay_style='cosine', make_vocab_size_divisible_by=128, max_inference_batch_size=12, max_memory_length=0,                             max_position_embeddings=1089, max_position_embeddings_finetune=-1, min_scale=1, model_parallel_size=1, new_dataset_path=None, no_load_optim=False, no_load_rng=False,             no_save_optim=False, no_save_rng=False, num_attention_heads=40, num_layers=48, num_pivot=256, num_workers=2, output_path='./samples', query_window=64, rank=2,                    reset_attention_mask=False, reset_position_ids=False, resume_dataloader=True, save='/hetu_group/wuxiangyu/cx/CogView_finetune/data/checkpoints/cogview-caption',                  save_interval=5000, seed=1234, shuffle=False, split='949,50,1', summary_dir='', temperature=1.0, test_data=None, time_interval=10, top_k=0, top_p=0.0, train_data=['./data/       ali_vqvae_hard_biggerset_011.lmdb'], train_iters=20000, txt_loss_scale=5.0, valid_data=None, vocab_size=58240, warmup=0.1, weight_decay=0.01, with_id=False, world_size=4)

**Comment by starmemda** [comment]
> @starmemda Could you provide your hyperparameters? both cogview and deepspeed.

**Comment by starmemda** [comment]
It seems that the link is an inference example. But I want to finetune.

**Comment by zhao0306** [comment]
Hello! if you can share the cogview-caption.zip? I can't download the document from WuDao now. Thank you. @starmemda
