### ISSUE TITLE
script to finetune Cogview-base

### ISSUE THREAD

**Issue by luyang-huang96** [THUDM/CogView#28]
Hi, I'm trying to finetune Cogview pretrained model. However, when I try to load model weights, I get following error:
RuntimeError: Error(s) in loading state_dict for GPT2Model:                                                                                                
        size mismatch for word_embeddings.weight: copying a param with shape torch.Size([14560, 2560]) from checkpoint, the shape in current model is torch
.Size([14592, 2560]).

Here is my script:

`NUM_WORKERS=1
NUM_GPUS_PER_WORKER=4
MP_SIZE=1

script_path=$(realpath $0)
echo $script_path
script_dir=$(dirname $script_path)
main_dir=$(dirname $script_dir)

OPTIONS_NCCL="NCCL_DEBUG=info"
HOST_FILE_PATH="hostfile_single"

config_json="$script_dir/ds_config_zero.json"
gpt_options=" \
       --experiment-name cogview-test_finetune \
       --img-tokenizer-num-tokens 8192 \
       --dataset-type TokenizedDataset \
       --model-parallel-size ${MP_SIZE} \
       --batch-size 4 \
       --num-layers 48 \
       --hidden-size 2560 \
       --num-attention-heads 40 \
       --save ./ \
       --train-iters 2000 \
       --save-interval 800 \
       --resume-dataloader \
       --train-data /path/to/my/data \
       --split 90,5,5 \
       --distributed-backend nccl \
       --lr-decay-style cosine \
       --warmup .1 \
       --checkpoint-activations \
       --deepspeed-activation-checkpointing \
       --max-position-embeddings 1089 \
       --max-memory-length 0 \
       --fp16 \
       --txt-loss-scale 5 \
       --load /path/to/cogview \
       --no-load-rng \
       --model-parallel-size 2 \
       --num-workers 16 \
       --is-sparse 0 \
       --finetune \
       --shuffle 
"

gpt_options="${gpt_options}
               --deepspeed \
               --deepspeed_config ${config_json} \
"

run_cmd="${OPTIONS_NCCL} deepspeed --num_nodes ${NUM_WORKERS} --num_gpus ${NUM_GPUS_PER_WORKER} --hostfile ${HOST_FILE_PATH} pretrain_gpt2.py $@ ${gpt_options}"
`

It will be great if you can provide some details for finetuning. Thanks!

**Comment by Sleepychord** [comment]
Hi, could you change the model_parallel_size back to 1 and try again? our released model use model_parallel_size=1

**Comment by luyang-huang96** [comment]
Thanks, it works for me on V100s! One more question: any recommendation of batch size for finetuning? currently I set "train_micro_batch_size_per_gpu=1" and "gradient_accumulation_steps"=8 for 8 32G V100s.

**Comment by Sleepychord** [comment]
Hi, It depends on your memory and total number of machines (if you are using ZeRO), so the best way may be to try by yourself.
