### ISSUE TITLE
The demo website is broken?

### ISSUE THREAD

**Issue by brianw0924** [THUDM/CogView#29]
請問為什麼那個 demo 網站輸入任何文字都說有非法內容

**Comment by Sleepychord** [comment]
非法内容指“色情、暴力、歧视、辱骂和政治敏感内容”，由于有人报告demo被用于不良用途，我们加大了关键字的判别力度，因此可能误伤正常的查询，非常抱歉。https://github.com/THUDM/CogView/issues/13

**Comment by brianw0924** [comment]
我連 倒立的貓咪 都被判成非法內容...

**Comment by Sleepychord** [comment]
改成简体中文似乎是可以的。
