### ISSUE TITLE
The math in this paper

### ISSUE THREAD

**Issue by brianw0924** [THUDM/CogView#30]
想請問一下關於此篇論文數學的部分:

1. 加入文字之後的 ELBO 有更詳細的推導過程嗎? 是不是單純把只有 image 的 ELBO 不等式兩邊各加上一個 NLL loss for text 而已?
因為我看起來 text 並沒有在 VQVAE 訓練過程中起到作用，而這個 ELBO 是給 VQVAE 的，不太懂為什麼會有 text 那項 loss
2. 不太了解 式(2) 如何變成 式(3) 的

謝謝

**Comment by Sleepychord** [comment]
1.加入文字之後的ELBO推導與之前無異，但是注意其他部分增加一個given t_i，并预先分离出文字部分的NLL，便可得到公式（2）。

**Comment by Sleepychord** [comment]
“因为我们在假设的生成过程的step（3）中，认为z已经完全拥有了文本的信息”--這裡我說的是隨機變量圖模型的“生成過程”，這裡是follow了VAE原文的說法，並不是指訓練過程。訓練過程第一階段沒有圖像參與，你可以理解為圖像的一個壓縮的過程。

如果沒有見到大象，顯然是不可能生成出大象了……但是可能學會組合，比如紅色+老虎之類的。

**Comment by brianw0924** [comment]
不太懂為什麼會說訓練過程第一階段沒有圖像參與? 第一階段不是用圖片訓練 VQ-VAE 嗎? 

--

那請問有沒有試過透過文字描述未知物體的外觀來讓他自我學習呢?

**Comment by Sleepychord** [comment]
@brianw0924 抱歉上个回复我笔误了，应该是没有文本参与。已经被NeurIPS 2021接受。
