### ISSUE TITLE
Layernorm form in paper

### ISSUE THREAD

**Issue by mzy97** [THUDM/CogView#31]
The formulation of layernorm in paper multiply a root_square(d) compare to layernorm introduced in pytorch document. Why add this multiplication? thank you
![image](https://user-images.githubusercontent.com/31816690/130483435-27dc95b5-21b1-4528-b850-740544497075.png)

**Comment by Sleepychord** [comment]
No, it is the original LayerNorm. Note d is the length of the vector x.
