### ISSUE TITLE
docker pull error, "You have reached your pull rate limit"

### ISSUE THREAD

**Issue by XuanxuanGao** [THUDM/CogView#32]
Is there any possibility to share the Dockerfile?

I was trying to use the docker since it's difficult to build the apex library. Whereas when I used docker pull like the below,
"docker pull cogview/cuda111_torch181_deepspeed040"

I got the following error message:
"Using default tag: latest
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"

Therefore, an original Dockerfile may be better.

**Comment by Sleepychord** [comment]
Hi, the dockerfile is already under env/, (although I am not 100% sure if it is the correct version).

**Comment by XuanxuanGao** [comment]
> Hi, the dockerfile is already under env/, (although I am not 100% sure if it is the correct version).

Thanks for the dockerfile! I change some components to make it suitable for my V100 GPU, and finally it works. The main changes are as follows:

cuda 10.1
cupy-cuda101
TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0+PTX 7.5+PTX"
torch-1.7.1+cu101
torchvision-0.8.2+cu101
