### ISSUE TITLE
can add english version of webpage demo

### ISSUE THREAD

**Issue by molo32** [THUDM/CogView#4]

**Comment by johnpaulbin** [comment]
This will require fine-tuning the model. It's possible, but probably not one of the higher priorities.

**Comment by Devetec** [comment]
It wouldn't, the website could be in English but the model would still only support Chinese. This would make it easier to use.

**Comment by Somefive** [comment]
We will look into this issue soon. As Devetec mentioned, the major problem here is that although we could support English website but it still cannot support English inputs for generating images. We will add more multilingual introductions to the website later. Thanks for the advice.

**Comment by PapayasTehSkeletor** [comment]
I am not sure if I would need to open a new Issue for this, so better to ask here. Sorry for my ignorance on the subject, but if the code comes out, would it be possible for someone to put it together with CLIP to generate things using English text? Or would the junction not work?

**Comment by Devetec** [comment]
@PapayasTehSkeletor That wouldn't work, as the model was only trained on Chinese text. CLIP is used for ranking images based on text captions, it would not be able to do that. You could put a translator in between your English text and CogView. That would be a functioning solution :)

**Comment by Somefive** [comment]
Currently, we add several minor modifications to the webpage for this issue.
1. The CogView model still **only supports simplified Chinese input texts** now. (Although it might be able to recognize limited English inputs)
2. For non-Chinese text inputs, the input box will show a **translate icon** which you can use to translate the input texts (like English, Japanese or other languages) into Chinese. (The translation is based on another commercial service that is not within our maintenance range. As a result, it is not expected to give a perfect translation to all inputs. If you are not sure if the translation is accurate, you can use Google Translate to translate back for further validation.)
3. There is a new button at the right of the *Show History* button, which can be used to **switch display language** between Chinese and English.

If there is any other further language issue for the website (not the pre-training model), please continue the discussion in this thread. Thanks for the advice.
