### ISSUE TITLE
微调图生文

### ISSUE THREAD

**Issue by yukeyiniupi** [THUDM/CogView#43]
请问在修改哪里的代码可以微调图生文，还是说修改数据集格式。
![image](https://user-images.githubusercontent.com/54205068/142553895-7cbba236-e248-4196-bfc6-4f6eae554c1a.png)

**Comment by yukeyiniupi** [comment]
> 请问在修改哪里的代码可以微调图生文，还是说修改数据集格式。 ![image](https://user-images.githubusercontent.com/54205068/142553895-7cbba236-e248-4196-bfc6-4f6eae554c1a.png)

**Comment by murray-z** [comment]
请问你解决了吗？如何微调图生文，以及数据如何处理？
