### ISSUE TITLE
docker pull failed

### ISSUE THREAD

**Issue by dh12306** [THUDM/CogView#44]
run docker pull cogview/cuda111_torch181_deepspeed040
result：
Using default tag: latest

Error response from daemon: manifest for cogview/cuda111_torch181_deepspeed040:latest not found

other question：
Could you tell me which version torch and cuda（nvcc -V) you use?

**Comment by yukeyiniupi** [comment]
可以自己用dockerfile创建一个docker环境
![image](https://user-images.githubusercontent.com/54205068/143569819-bf8fe34f-5322-4fee-a07b-a7a0a3686c3a.png)
