### ISSUE TITLE
How to resume?

### ISSUE THREAD

**Issue by haoli-zbdbc** [THUDM/CogView#66]
Hi, I want to know how to recover training from the checkpoint file. I did not find this option in the configuration file, only "-- resume dataloader". Additionally, I trained on my own dataset (only 1800 images), and although I set "-- train iters" to 200000, the training automatically stopped at 50000, and the error message is shown in the figure:
![图片](https://github.com/THUDM/CogView/assets/50076227/7a2f85e9-bc93-42cc-b735-9b9567b8061b)

**Comment by 1049451037** [comment]
For resume training, you just need to replace the `--from_pretrained` to your checkpoint path.

For StopIteration, I also faced the same problem recently... It's a bug of sat, and I'm working on fixing it.

By the way, 1800 images do not worth 50000 training iters...

**Comment by haoli-zbdbc** [comment]
OK, Thank you very much!! @1049451037
